set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-kitty:RGB:clipboard:focus:extkeys:hyperlinks:mouse:osc7:sync"
set -g allow-passthrough on
set -s set-clipboard on
set -s focus-events on
set -s extended-keys on
set -s extended-keys-format csi-u

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection
set -g mouse on
bind -T copy-mode-vi WheelUpPane send-keys -X -N 1 scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X -N 1 scroll-down

set -g mode-style reverse
set -g status-interval 0
set -g status-style "fg=default,bg=default"
set -g status-right "#{?client_prefix,[PREFIX],[NORMAL]}"

bind -n C-M-w choose-tree -Zw
bind -n C-M-c new-window
bind -n C-M-d detach-client

bind -n C-M-1 select-window -t :=1
bind -n C-M-2 select-window -t :=2
bind -n C-M-3 select-window -t :=3
bind -n C-M-4 select-window -t :=4
bind -n C-M-5 select-window -t :=5
bind -n C-M-6 select-window -t :=6
bind -n C-M-7 select-window -t :=7
bind -n C-M-8 select-window -t :=8
