font_family Source Code Pro
disable_ligatures always
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13

remember_window_size no
window_padding_width 0 12
initial_window_width 120c
initial_window_height 37c
tab_title_template "{index}:{title}"
tab_bar_style separator
tab_separator " │ "
tab_bar_min_tabs 1
tab_switch_strategy right
macos_show_window_title_in window

macos_option_as_alt both
repaint_delay 50
input_delay 50

clipboard_control write-clipboard read-clipboard

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+t       new_tab
map cmd+shift+t new_tab_with_cwd
map cmd+left          send_key ctrl+a
map cmd+right         send_key ctrl+e
map option+left       send_key alt+b
map option+right      send_key alt+f
map cmd+backspace     send_key ctrl+u
map option+backspace  send_key alt+backspace
map cmd+delete        send_key ctrl+k
map option+delete     send_key alt+d

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME
